package LeetCode.Strings;

public class FindTheDiffernce389 {
//    You are given two strings s and t.
//
//    String t is generated by random shuffling string s and then add one more letter at a random position.
//
//    Return the letter that was added to t.
//
//
//
//    Example 1:
//
//    Input: s = "abcd", t = "abcde"
//    Output: "e"
//    Explanation: 'e' is the letter that was added.
//    Example 2:
//
//    Input: s = "", t = "y"
//    Output: "y"
    public char findTheDifference(String s, String t){
        return 'n';
    }

    public static void main(String[] args) {
        FindTheDiffernce389 solver = new FindTheDiffernce389();
        System.out.println(solver.findTheDifference("abcd", "abcde"));

    }
}
